package com.wifi.vivoguide.event;

public enum SystemEventConst {
    EVENT_SHOW_CONNECTING_WIFI_INFO,
    EVENT_SHOW__WIFI_CONNECT_CONTAINER_VIEW,
    EVENT_HIDE_WIFI_CONNECT_CONTAINER_VIEW,
    EVENT_INPUT_STATIC_SET_VALUE,
    EVENT_HIDE_CHOOSE_SERVICE_VIEW,
    EVENT_COMPLETE_GUIDE,
    EVENT_SHOW_WIFI_CONNECT_DIALOG_VIEW,
    EVENT_SHOW_LONG_CLICK_VIEW,


}
